DataEntryTool/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from ahdms.views.home_view import HomeView, AWSImageDownloadView, AWSFetchAWSResource, DocumentFormSubmitView, FetchEntityView, \
    PingResourceView, SkipResourceView
from ahdms.views.maintanence_views import RunMigrationsView
from ahdms.views.manage_views import DocumentListView, ManageUserCreateView, FetchAllSubmissionView, \
    FetchDocumentSubmissionContent, DocumentEditView, ApproveDocumentSubmission, ManageDocumentFetchListView, \
    DocumentUploadView, ManageDocumentListView, ManageDocumentPreview

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^aws-resource-download/$', AWSImageDownloadView.as_view(), name='aws_resource_download'),
    url(r'fetch-next-resource/$', AWSFetchAWSResource.as_view(), name='aws_fetch_next_resource'),
    url(r'fetch-resource/$', AWSFetchAWSResource.as_view(), name='aws_fetch_resource'),
    url(r'ping-resource/$', PingResourceView.as_view(), name='aws_ping_resource_view'),
    url(r'skip-resource/$', SkipResourceView.as_view(), name='aws_skip_resource_view'),
    url(r'manage/submissions/(?P<doc_type>[^/]+)/(?P<doc_id>[^/]+)/$', FetchAllSubmissionView.as_view(),
        name='aws_fetch_all_submissions_view'),
    url(r'manage/document-content/(?P<doc_type>[^/]+)/$', FetchDocumentSubmissionContent.as_view(),
        name='aws_fetch_submission_content_view'),
    url(r'manage/edit/documents/(?P<doc_type>[^/]+)/(?P<pk>\d+)/$', DocumentEditView.as_view(),
        name='aws_manage_edit_content_view'),
    url(r'manage/preview/documents/(?P<doc_type>[^/]+)/(?P<pk>\d+)/$', ManageDocumentPreview.as_view(),
        name='aws_manage_preview_content_view'),
    url(r'document-submit/$', DocumentFormSubmitView.as_view(), name="document_submit_view"),
    url(r'manage/document-fetch/$', ManageDocumentFetchListView.as_view(), name="manage_document_fetch_view"),
    url(r'document-submit/handle-action/(?P<action_type>[^/]+)$', ApproveDocumentSubmission.as_view(),
        name="document_submit_action_view"),
    url(r'fetch-entities/$', FetchEntityView.as_view(), name="document_fetch_view"),
    url(r'manage/document-list/$', ManageDocumentListView.as_view(), name="manage_document_list_view"),
    url(r'manage/upload-document/$', DocumentUploadView.as_view(), name="manage_document_upload_view"),
    url(r'manage/(?P<manage_area>[^/]+)/$', DocumentListView.as_view(),
        name="manage_view"),
    url(r'manage/users/create/$', ManageUserCreateView.as_view(),
        name="manage_users_create_view"),
    # url(r'^save_data/', views.save_data, name='save_data'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^run-migrations/', RunMigrationsView.as_view(),
        name="management_run_migrations"),
]

DataEntryTool/ahdms/models/document.py
from django.contrib.auth.models import User
from django.db import models

from ahdms.helpers.enums import MatchFieldType
from ahdms.models.facility import Facility
from ahdms.models.physician import Physician
from core.models.base_entity import BaseEntity
from ahdms.models.document_type import DocumentType
from ahdms.models.patient import Patient


class Document(BaseEntity):
    user = models.ForeignKey(User)
    patients = models.ManyToManyField(Patient)
    facilities = models.ManyToManyField(Facility)
    physicians = models.ManyToManyField(Physician)
    type = models.ForeignKey(DocumentType)
    comment = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=100)
    processed_document_id = models.IntegerField(default=0)
    notes = models.TextField(blank=True, null=True)

    def get_doc_type_verbal(self):
        return self.type.doc_type

    def get_match_field_regular(self):
        REGULAR = {
            "type": MatchFieldType.REGULAR.value,
            "fields": None
        }
        return REGULAR

    def get_match_field_m2m(self, fields=[]):
        M2M = {
            "type": MatchFieldType.M2M.value,
            "fields": fields
        }
        return M2M

    def get_match_fields(self):
        return {
            # "user_id": { "type": "regular", "fields": None or [] }
            # #type can be MatchFieldType.REGULAR, MatchFieldType.M2M, MatchFieldType.FKEY
        }

    class Meta:
        abstract = True

DataEntryTool/ahdms/models/document_type.py
from django.db import models
from core.models.base_entity import BaseEntity


class DocumentType(BaseEntity):
    doc_type = models.CharField(max_length=200)

    class Meta:
        app_label = 'ahdms'
        
    @classmethod
    def get_all_document_types(cls):
        doc_type_objects = cls.objects.all()
        d = {}
        for doc_type_object in doc_type_objects:
            d[doc_type_object.doc_type] = doc_type_object
        return d

DataEntryTool/ahdms/models/document_upload.py
import os
from django.contrib.auth.models import User
from django.db import models
from ahdms.helpers.enums import RequestSource
from ahdms.models.aws_resource import AWSResource
from ahdms.models.document_type import DocumentType
from core.models.base_entity import BaseEntity
from django.conf import settings


class DocumentUpload(BaseEntity):
    document = models.ForeignKey(DocumentType)
    original_file_name = models.CharField(max_length=500, null=True, blank=True)
    file_name = models.CharField(max_length=500, null=True, blank=True)
    file = models.FileField(max_length=500, upload_to=os.path.join(settings.MEDIA_ROOT, "uploads"))
    is_approved = models.BooleanField(default=False)
    approved_by = models.ForeignKey(User, null=True)
    request_source = models.CharField(max_length=200, default=RequestSource.WEB.value)
    aws_upload_status = models.BooleanField(default=False)
    aws_resource = models.ForeignKey(AWSResource, null=True)

DataEntryTool/ahdms/models/patient.py
from django.db import models
from core.models.base_entity import BaseEntity


class Patient(BaseEntity):
    name = models.CharField(max_length=128, blank=True, null=True)
    patient_id = models.CharField(max_length=128, blank=True, null=True)
    age = models.CharField(max_length=10, blank=True, null=True)
    gender = models.CharField(max_length=100, null=True, blank=True)  # Gender.MALE.value
    date_of_birth = models.DateField(max_length=128, blank=True, null=True)
    phone = models.CharField(max_length=128, blank=True, null=True)
    weight = models.DecimalField(max_digits=20, decimal_places=2, null=True, blank=True)
    height = models.DecimalField(max_digits=20, decimal_places=2, null=True, blank=True)
    systolic = models.DecimalField(max_digits=20, decimal_places=2, null=True, blank=True) # For bp like 120/80, 120 is the systolic and 80 is the diastolic
    diastolic = models.DecimalField(max_digits=20, decimal_places=2, null=True, blank=True)
    bp = models.CharField(max_length=128, blank=True, null=True)

    class Meta:
        app_label = 'ahdms'

DataEntryTool/core/models/base_entity.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User

from core.manager.modelmanager.base_entity_manager import BaseEntityModelManager
from core.models.code_pointer import CodePointer
from engine.clock import Clock


class BaseEntity(models.Model):
    code = models.CharField(max_length=50)
    date_created = models.DateTimeField()
    last_updated = models.DateTimeField()
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='+', null=True)
    last_updated_by = models.ForeignKey(User, related_name='+', null=True)

    objects = BaseEntityModelManager(filter={"is_deleted": False})

    def date_created_verbose(self):
        return self.date_created.strftime("%d/%m/%Y")

    def get_code_prefix(self):
        prefix = ''.join([c for c in self.__class__.__name__ if c.isupper()])
        return prefix if prefix else self.__class__.__name__

    def field_name_as_verbose(self, field_name):
        return " ".join(field_name.split("_"))

    def as_text(self, fields=[], m2m_fields={}, date_formats={}, labels={}):
        text = ""
        m2m_names = m2m_fields.keys()
        for field in fields:
            field_split_colon = field.split(":")
            field_label = None
            if len(field_split_colon) >= 2:
                field = field_split_colon[0]
                field_label = self.field_name_as_verbose(field_split_colon[1])
            if "__" in field:
                field_split = field.split("__")
                f_key = field_split[0]
                f_key_field_name = field_split[1]
                f_field = getattr(self, f_key)
                if f_field:
                    f_field_value = getattr(f_field, f_key_field_name)
                    if field_label:
                        text += field_label + ": " + f_field_value if f_field_value else ""
                        text += "\n"
                    else:
                        value = self.field_name_as_verbose(f_key) + " " + self.field_name_as_verbose(f_key_field_name) + ":" + f_field_value if f_field_value else ""
                        text += value + "\n"
                else:
                    if field_label:
                        text += field_label + ":" + " \n"
                    else:
                        text += self.field_name_as_verbose(f_key) + " " + self.field_name_as_verbose(f_key_field_name) + ": \n"
            else:
                if field in m2m_names:
                    if field_label:
                        text += field_label + ":\n"
                    else:
                        text += self.field_name_as_verbose(field.capitalize()) + ":\n"
                    m2m_cols = m2m_fields.get(field)
                    m2m_field = getattr(self, field)
                    m2m_objects = m2m_field.all()
                    for m2m_object in m2m_objects:
                        text += m2m_object.as_text(fields=m2m_cols) + "\n"
                else:
                    value = getattr(self, field)
                    if value:
                        date_fmt_found = False
                        for field_name, date_format in date_formats.items():
                            if field_name == field:
                                date_fmt_found = True
                                value_type = type(value)
                                now_date = datetime.now().date()
                                datetime_instance = type(value) == type(now_date)
                                if datetime_instance:
                                    value = value.strftime(date_format)
                                    if field_label:
                                        text += field_label + ": " + value + "\n"
                                    else:
                                        text += self.field_name_as_verbose(field) + ": "+ value + "\n"
                                else:
                                    datetime_instance = datetime.strptime(str(value), date_format)
                                    value = datetime_instance.strftime(date_format)
                                    if field_label:
                                        text += field_label + ": " + value + "\n"
                                    else:
                                        text += self.field_name_as_verbose(field) + ": "+ value + "\n"
                        if not date_fmt_found:
                            if field_label:
                                text += field_label + ": " + str(value) + "\n"
                            else:
                                text += self.field_name_as_verbose(field) + ": "+ str(value) + "\n"
                    else:
                        if field_label:
                            text += field_label + ":\n"
                        else:
                            text += self.field_name_as_verbose(field) + ":\n"
        return text
        
    def as_json(self, fields=[], date_formats={}):
        data = {}
        try:
            for field in fields:
                value = getattr(self, field)
                if value:
                    for field_name, date_format in date_formats.items():
                        if field_name == field:
                            value_type = type(value)
                            now_date = datetime.now().date()
                            datetime_instance = type(value) == type(now_date)
                            if datetime_instance:
                                value = value.strftime(date_format)
                                data[field] = value
                            else:
                                datetime_instance = datetime.strptime(str(value), date_format)
                                value = datetime_instance.strftime(date_format)
                                data[field] = value
                    else:
                        data[field] = str(value)
                else:
                    data[field] = ""
        except Exception as exp:
            return {}
        return data

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):

        if not self.pk:
            self.date_created = Clock.utc_datetime()

            last_code_objects = CodePointer.objects.filter(model_name=self.__class__.__name__)
            if not last_code_objects.exists():
                last_code_object = CodePointer()
                last_code_object.model_name = self.__class__.__name__
                last_code_object.value = 1
                last_code_object.save()
            else:
                last_code_object = last_code_objects.first()
                last_code_object.model_name = self.__class__.__name__
                last_code_object.value += 1
                last_code_object.save()

            self.code = self.get_code_prefix() + "-" + str(format(last_code_object.value, '08d'))

        self.last_updated = Clock.utc_datetime()
        super(BaseEntity, self).save(force_insert, force_update, using, update_fields)

    class Meta:
        abstract = True

DataEntryTool/templates/document.html
{% extends 'base/master.html' %}
{% load staticfiles %}
{% block body_content %}
{% include "sections/manage_top_menu.html" %}
{% if is_manage == 1 %}
<div class="row">
    <div class="col-md-12" style="padding-bottom: 20px !important;">
        {% if preview %}
        <h4 style="font-weight: bold !important;">Document View</h4>
        {% else %}
        <h4 style="font-weight: bold !important;">Document Edit</h4>
        {% endif %}
        <p>Document ID: {{ document_id }}</p>
    </div>
</div>
{% endif %}
<div id="id_loading_container" class="text-center">
    <div class="loader"></div>
    <h3>Loading...</h3>
</div>
<div class="row" data-manage="{% if is_manage %}{{ is_manage }}{% else %}0{% endif %}"
     id="id_resource_container" data-resource-skip-url="{% url "aws_skip_resource_view" %}"
data-resource-id="{{ resource_id }}" data-resource-ping-url="{% url "aws_ping_resource_view" %}"
style="display: none;" data-doc-type="{{ resource_type }}" data-doc-id="{{ doc_id }}"
     data-resource-download-url="{% url "aws_resource_download" %}"
data-next-resource-url="{% url "aws_fetch_next_resource" %}">
    <div class="col-md-7">
        <div class="row">
            <div id="id_resource_image_container" class="col-md-12 doc-img-container">
                <input type="hidden" id="id_aws_resource_id_global"/>
                <div class="img-text-container text-center">
                  <h4>Patient ID:
                      <span id="id_patient_id">{% if patient_id %}{{ patient_id }}{% endif %}</span></h4>
                </div>
                <img id="id_resource_url" src="{% if resource_url %}{{ resource_url }}{% else %}#{% endif %}" alt="Document" style="width:100%">
            </div>
        </div>
        <div class="row">

        </div>
    </div>
    <div class="col-md-5 document-form-area" id="id_document_form_container">
        <div class="doc_type_container">
          <select class="form-control" required="required" name="doc_type" id="id_doc_type">
              <option value="">Select Document Type</option>
              {% for doc_type_object in document_type_objects %}
                <option value="{{ doc_type_object.doc_type }}" {% if resource_type == doc_type_object.doc_type %}selected{% endif %}>{{ doc_type_object.doc_type }}</option>
              {% endfor %}
          </select>
        </div>

        {% for form_name, rendered_form in document_forms.items %}
        <div id="id_{{ form_name }}" class="document-form hide">
        {{ rendered_form }}
        </div>
        {% endfor %}
    </div>
</div>
<div class="row" style="display: none;">
    <div class="col-md-12">
        <div class="col-md-12 pagn-container">
            <a href="#" class="next round pagn pull-right skip-btn">Skip >></a>
        </div>
    </div>
</div>
{% endblock body_content %}

{% block scripts %}
<link rel="stylesheet" type="text/css" href="{% static "css/form_handles.css" %}"/>
<script src="{% static "js/vendor/jquery.sticky.js" %}"></script>
<script src="{% static "js/form_handles.js" %}"></script>
{% include "sections/form_loader.html" %}
<style type="text/css">
    {% if preview %}
{#        [readonly="readonly"],#}
{#        [readonly="readonly"]:focus,#}
{#        select[readonly="readonly"],#}
{#        select[readonly="readonly"]:focus,#}
{#        input[readonly="readonly"],#}
{#        input[readonly="readonly"]:focus,#}
{#        .content input[type="text"][readonly]:focus,#}
{#        textarea[readonly]:focus,#}
{#        select[readonly]:focus,#}
{#        .form-control[disabled], .form-control[readonly], fieldset[disabled]{#}
{#            background: none repeat scroll 0 0 transparent!important;#}
{#            border: medium none !important;#}
{#            color: #000000!important;#}
{#        }#}
    .form-control-proxy {
        display: block;
        width: 100%;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.42857143;
        color: #555;
        background-color: #fff;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
    }
    .form-control-proxy[disabled], .form-control-proxy[readonly], fieldset[disabled] .form-control-proxy {
        background-color: #eee;
        opacity: 1;
    }
    {% endif %}
</style>
<script>
$(document).ready(function () {
    //For Preview
    {% if preview %}
    $("#id_document_form_container").find(".form-control").each(function (index) {
        if($(this).is(":visible") || !$(this).isDisabled) {
            $(this).prop("readonly", "readonly");
            //$(this).replaceWith("<label>"+ $(this).val() +"</label>");
        }
    });
    $("#id_document_form_container").find("select").removeClass("form-control").addClass("form-control-proxy").prop("disabled", true);
    {% endif %}
});
</script>
{% endblock scripts %}

DataEntryTool/templates/document_upload.html
{% extends 'manage.html' %}
{% load staticfiles %}
{% load ds %}
{% block manage_content %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <!--<div class="list-group panel">-->
                <!--<h4 class="panel-heading">Manage Users</h4>-->
                <!--<a class="list-group-item main-menu-item-head" href="{% url 'account_signup' %}">Create New User</a>-->
                <!--<a class="list-group-item main-menu-item-head" href="#">View/Edit Users</a>-->
            <!--</div>-->
            <div class="list-group panel">
                <h4 class="panel-heading">Upload Documents</h4>
                <a class="list-group-item main-menu-item-head {% if active_left_item == "upload" %}doc-active{% endif %}" href="{% url "manage_view" "document-upload" %}">Upload Documents</a>
                <a class="list-group-item main-menu-item-head {% if active_left_item == "approve" %}doc-active{% endif %}" href="{% url "manage_document_list_view" %}">Pending Approval</a>
            </div>
            <div class="list-group panel">
                <h4 class="panel-heading">Manage Documents</h4>
                <a class="list-group-item main-menu-item-head {% if active_left_item == "no" %}doc-active{% endif %}" href="{% url "manage_view" "documents" %}?filter=no">All Documents</a>
                <a class="list-group-item main-menu-item-head {% if active_left_item == "archived" %}doc-active{% endif %}" href="{% url "manage_view" "documents" %}?filter=archived">Archived Documents</a>
                <a class="list-group-item main-menu-item-head {% if active_left_item == "processed" %}doc-active{% endif %}" href="{% url "manage_view" "documents" %}?filter=processed">Processed Documents</a>
                <a class="list-group-item main-menu-item-head {% if active_left_item == "assigned" %}doc-active{% endif %}" href="{% url "manage_view" "documents" %}?filter=assigned">Assigned Documents</a>
                <a class="list-group-item main-menu-item-head {% if active_left_item == "unassigned" %}doc-active{% endif %}" href="{% url "manage_view" "documents" %}?filter=unassigned">Unassigned Documents</a>
            </div>
        </div>
        <div class="col-md-9">
            <h3>Upload Document</h3>
            <form name="document_upload_form" id="id_document_upload_form"
                  enctype="multipart/form-data" method="POST"
                  action="{% url "manage_document_upload_view" %}">
                <table class="table" cellspacing="0" width="90%">
                    <tbody>
                        <tr>
                            <td class="align-right">
                                Select Document Type
                            </td>
                            <td class="align-left">
                                {% csrf_token %}
                                {{ form.document }}
                            </td>
                        </tr>
                        <tr>
                            <td class="align-right">
                                Browse File
                            </td>
                            <td class="align-left">
                                {{ form.file }}
                            </td>
                        </tr>
                        <tr>
                            <td class="align-right">
                                Is Approved
                            </td>
                            <td class="align-left">
                                {{ form.is_approved }}
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <br/>
                                <button style="width: 140px; " class="btn btn-primary btn-sm pull-right">Upload</button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </form>
        </div>
    </div>
</div>
{% endblock manage_content %}
{% block scripts %}

    <style type="text/css">
        .main-menu-item-head {
            text-align: left;
        }
        .main-menu-item {
            font-size: 18px;
            font-weight: bold;
            text-align: left;
        }
        .child-item {
            text-align: left;
            padding-left: 40px;
        }
        .child-item {
            text-decoration: none;
        }
        .align-left {
            text-align: left !important;
        }
        .align-right {
            text-align: right !important;
        }
        .doc-active {
            font-weight: bold;
        }
        #id_document_upload_form tr td {
            text-align: left !important;
        }
    </style>
    <script type="text/javascript">

    </script>
{% endblock scripts %}

DataEntryTool/templates/manage.html
{% extends 'base/master.html' %}
{% block header2 %}
{% include "sections/manage_top_menu.html" %}
{% endblock header2 %}
{% block body_content %}
<div class="row" id="id_resource_container">
{% block manage_content %}

{% endblock manage_content %}
</div>
{% endblock body_content %}

DataEntryTool/templates/manage_document_update.html
{% extends 'manage.html' %}
{% load staticfiles %}
{% block body_content %}
{% if is_manage == 1 %}
<div class="row">
    <div class="col-md-12" style="padding-bottom: 20px !important; font-weight: bold !important;">
        <h4>Document Edit</h4>
    </div>
</div>
{% endif %}
<div id="id_loading_container" class="text-center">
    <div class="loader"></div>
    <h3>Loading...</h3>
</div>
<div class="row" data-manage="{% if is_manage %}{{ is_manage }}{% else %}0{% endif %}" id="id_resource_container" data-resource-skip-url="{% url "aws_skip_resource_view" %}" data-resource-id="" data-resource-ping-url="{% url "aws_ping_resource_view" %}" style="display: none;"
     data-resource-download-url="{% url "aws_resource_download" %}" data-next-resource-url="{% url "aws_fetch_next_resource" %}">
    <div class="col-md-7">
        <div class="row">
            <div id="id_resource_image_container" class="col-md-12 doc-img-container">
                <input type="hidden" id="id_aws_resource_id_global"/>
                <div class="img-text-container text-center">
                  <h4>Patient ID:
                      <span id="id_patient_id"></span></h4>
                </div>
                <img id="id_resource_url" src="#" alt="Document" style="width:100%">

            </div>
        </div>
        <div class="row">

        </div>
    </div>
    <div class="col-md-5 document-form-area" id="id_document_form_container">
        <div class="doc_type_container">
          <select class="form-control" required="required" name="doc_type" id="id_doc_type">
              <option value="">Select Document Type</option>
              {% for doc_type_object in document_type_objects %}
                <option value="{{ doc_type_object.doc_type }}" {% if resource_type == doc_type_object.doc_type %}selected{% endif %}>{{ doc_type_object.doc_type }}</option>
              {% endfor %}
          </select>
        </div>

        {% for form_name, rendered_form in document_forms.items %}
        <div id="id_{{ form_name }}" class="document-form hide">
        {{ rendered_form }}
        </div>
        {% endfor %}
    </div>
</div>
<div class="row" style="display: none;">
    <div class="col-md-12">
        <div class="col-md-12 pagn-container">
            <a href="#" class="next round pagn pull-right skip-btn">Skip >></a>
        </div>
    </div>
</div>
{% endblock body_content %}
{% block scripts %}
<link rel="stylesheet" type="text/css" href="{% static "css/form_handles.css" %}"/>
<script src="{% static "js/vendor/jquery.sticky.js" %}"></script>
<script src="{% static "js/form_handles.js" %}"></script>
{% include "sections/form_loader.html" %}
{% endblock scripts %}

DataEntryTool/templates/manage_documents.html
{% extends 'manage.html' %}
{% load staticfiles %}
{% block manage_content %}
<link rel="stylesheet" href="{% static "/css/vendor/jquery.dataTables.min.css" %}">
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <table id="id_document_table" class="display" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>First name</th>
                        <th>Last name</th>
                        <th>Position</th>
                        <th>Office</th>
                        <th>Salary</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Tiger</td>
                        <td>Nixon</td>
                        <td>System Architect</td>
                        <td>Edinburgh</td>
                        <td>$320,800</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% include "documents/unmatch_diff_view.html" %}
{% endblock manage_content %}
{% block scripts %}
    <script src="{% static "js/vendor/jquery.dataTables.min.js" %}"></script>
    <style type="text/css">

    </style>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#id_document_table').DataTable();
        });
    </script>
{% endblock scripts %}

DataEntryTool/templates/manage_users_create.html
{% extends 'manage_users.html' %}
{% block manage_content2 %}
<div class="row">
    <div class="col-md-12">
            <h4 style="text-align: left; margin-left: 40px; ">Create New User</h4>
            <hr/>
            <form method="POST" action="{% url 'manage_users_create_view' %}" id="id_signup_form">
            {% csrf_token %}
            <table class="table">
                <tbody>
                    <tr>
                        <td>
                            {{ signup_form.username }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            {{ signup_form.email }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            {{ signup_form.password }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            {{ signup_form.password2 }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            {{ signup_form.is_active }} <label for="id_is_active">Is Active</label>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div>
                <button class="btn btn-lg btn-primary btn-block submit">Create User</button>
            </div>
            <div class="clearfix"></div>
        </form>
    </div>
</div>
<table class="table">
    <tbody>
        <tr>
            <td>

            </td>
        </tr>
    </tbody>
</table>
<style type="text/css">
    #id_signup_form {
        max-width: 400px !important;
        margin-left: 40px;
    }
    .shadow-container {
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
      text-align: center;
      padding: 20px 20px 40px 20px !important;
    }
</style>
{% endblock manage_content2 %}